name: ci

on:
  push:
  pull_request:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Try wheels-only first for speed/reliability; if a wheel is missing, fall back once.
      - name: Install dependencies (prefer wheels)
        run: |
          set -eux
          # If this fails, try again without wheel restriction
          (PIP_ONLY_BINARY=":all:" pip install -r requirements.txt) || pip install -r requirements.txt

      - name: Environment debug
        run: |
          python -V
          python -m pip debug --verbose
          python - << 'PY'
import sys, platform
print("exe:", sys.executable)
print("platform:", platform.platform())
PY
          echo "----- pip freeze -----"
          pip freeze

      - name: Import checks (numpy / scipy / sklearn)
        run: |
          python - << 'PY'
import numpy, scipy, sklearn
print("numpy", numpy.__version__)
print("scipy", scipy.__version__)
print("sklearn", sklearn.__version__)
PY

      # Ensure the sample corpus committed with the repo is present
      - name: Check repo structure (data/corpus present)
        run: |
          ls -la
          test -d data/corpus
          test -f data/corpus/policy_foia.md
          test -f data/corpus/prior_response_1.md
          test -f data/corpus/prior_response_2.md

      # Final CLI smoke test – prints first line of JSON so logs stay short
      - name: CLI smoke test (single request)
        run: |
          python -m app.main --text "Test email records request to the Mayor's Office from Jan 2023." | sed -n '1p'
