name: ci

on:
  push:
  pull_request:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install deps using prebuilt wheels only (fast & reliable on Actions)
      - name: Install dependencies (wheels only)
        env:
          PIP_ONLY_BINARY: ":all:"   # refuse to build from source
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Quick sanity print so logs show versions and interpreter path
      - name: Quick environment report
        run: |
          python -V
          python - << 'PY'
import numpy, sklearn, sys
print("numpy", numpy.__version__, "| sklearn", sklearn.__version__)
print("exe", sys.executable)
PY

      # Ensure sample data exists in the repo (your app expects these)
      - name: Check repo structure (data/corpus present)
        run: |
          ls -la
          test -d data/corpus
          test -f data/corpus/policy_foia.md
          test -f data/corpus/prior_response_1.md
          test -f data/corpus/prior_response_2.md

      # Smoke test your CLI (no GPU / no network)
      - name: CLI smoke test (single request)
        run: |
          python -m app.main --text "Test email records request to the Mayor's Office from Jan 2023." | head -n 1
